defaults: &defaults
  working_directory: /home/circleci/.go_workspace/src/github.com/gruntwork-io/package-terraform-utilities
  machine:
    image: circleci/classic:201808-01

version: 2.0
jobs:
  test aws:
    <<: *defaults
    steps:
      - checkout
      - run: &install_gruntwork_tooling
          name: install gruntwork tooling
          command: |
            curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version v0.0.21
            gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "v0.13.3"
            gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "v0.13.20"
            configure-environment-for-gruntwork-module --circle-ci-2 --use-go-dep --go-src-path test --terragrunt-version NONE

      - run:
          name: run tests (with python2)
          command: |
            mkdir -p /tmp/logs/python2
            echo "Using python 2"
            pyenv global 2.7.12
            python --version
            run-go-tests --circle-ci-2 | tee /tmp/logs/python2/all.log

      - run:
          name: run tests (with python3)
          command: |
            mkdir -p /tmp/logs/python3
            echo "Using python 3"
            pyenv global 3.5.2
            python --version
            run-go-tests --circle-ci-2 | tee /tmp/logs/python3/all.log

      - run:
          command: |
            terratest_log_parser --testlog /tmp/logs/python2/all.log --outputdir /tmp/logs/python2
            terratest_log_parser --testlog /tmp/logs/python3/all.log --outputdir /tmp/logs/python3
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - test aws:
          filters:
            tags:
              only: /^v.*/
